name: Build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  BUILD_TYPE: Debug

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: >
          sudo apt-get update --yes &&
          sudo apt-get install --yes --no-install-recommends
          libx11-dev
          libxi-dev
          libxcursor-dev
          libgl1-mesa-dev
          spirv-cross
          spirv-tools

      - name: Fetch Slang
        run: |
          wget -q --show-progress --progress=bar:force:noscroll -O ./slang.tar.gz \
            https://github.com/shader-slang/slang/releases/download/v2025.5/slang-2025.5-linux-x86_64.tar.gz
          mkdir slang
          tar -xf slang.tar.gz --directory=./slang
          sudo cp ./slang/bin/* /usr/local/bin
          sudo cp ./slang/lib/* /usr/local/lib
          slangc -version

      - name: CMake Configure (GCC)
        run: >
          cmake 
          -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_COMPILER=gcc

      - name: CMake Build (GCC)
        run: cmake --build ${{github.workspace}}/build

      - name: CMake Configure (Clang)
        run: >
          cmake 
          -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_C_COMPILER=clang

      - name: CMake Build (Clang)
        run: cmake --build ${{github.workspace}}/build
