name: build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  BUILD_TYPE: Debug

jobs:
  build-ubuntu-gcc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: >
       sudo apt-get update --yes &&
       sudo apt-get install --yes --no-install-recommends
       libx11-dev
       libxi-dev
       libxcursor-dev
       libgl1-mesa-dev
       glslang-tools
       spirv-cross

    - name: Configure CMake
      run: > 
        cmake 
        -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_CXX_COMPILER=g++
        -DCMAKE_C_COMPILER=gcc

    - name: Build
      run: cmake --build ${{github.workspace}}/build

  build-ubuntu-clang:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: >
       sudo apt-get update --yes &&
       sudo apt-get install --yes --no-install-recommends
       libx11-dev
       libxi-dev
       libxcursor-dev
       libgl1-mesa-dev
       glslang-tools
       spirv-cross

    - name: Configure CMake
      run: > 
        cmake 
        -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_C_COMPILER=clang

    - name: Build
      run: cmake --build ${{github.workspace}}/build
